<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/19 13:25:59

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=concurso;host=localhost',
  'username' => 'root',
  'password' => 'avalancha',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
