<?php


/**
 * Skeleton subclass for performing query and update operations on the 'entry' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri Oct 29 13:36:04 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EntryPeer extends BaseEntryPeer {
  public static function retrieveBySlug($slug, PropelPDO $con = null)
  {

    if (null !== ($obj = EntryPeer::getInstanceFromPool((string) $slug))) {
      return $obj;
    }

    if ($con === null) {
      $con = Propel::getConnection(EntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
    }

    $criteria = new Criteria(EntryPeer::DATABASE_NAME);
    $criteria->add(EntryPeer::SLUG, $slug);

    $v = EntryPeer::doSelect($criteria, $con);

    return !empty($v) > 0 ? $v[0] : null;
  }

  public static function getPublishedEntries($num = null)
  {
    $criteria = new Criteria();
    $criteria->add(EntryPeer::PUBLISHED, 1);
    if($num !== null)
    {
      $criteria->setLimit($num);
    }
    $criteria->addDescendingOrderByColumn('created_at');
    $entries = EntryPeer::doSelect($criteria);

    return $entries;
  }
  public static function getPublishedCriteria()
  {
    $criteria = new Criteria();
    $criteria->add(EntryPeer::PUBLISHED, 1);
    $criteria->addDescendingOrderByColumn('created_at');
  }
} // EntryPeer
