<?php


/**
 * Skeleton subclass for performing query and update operations on the 'evaluation' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri Nov 12 11:55:53 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EvaluationPeer extends BaseEvaluationPeer {

    public static function retrieveByProjectJuryId($project_jury_id, PropelPDO $con = null)
    {

        if (null !== ($obj = EvaluationPeer::getInstanceFromPool((string) $project_jury_id))) {
            return $obj;
        }

        if ($con === null) {
            $con = Propel::getConnection(EvaluationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria = new Criteria(EvaluationPeer::DATABASE_NAME);
        $criteria->add(EvaluationPeer::PROJECT_JURY_ID, $project_jury_id);

        $v = EvaluationPeer::doSelect($criteria, $con);

        return !empty($v) > 0 ? $v[0] : null;
    }
} // EvaluationPeer
