<?php


/**
 * Skeleton subclass for representing a row from the 'eval_question' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri Nov 19 10:55:17 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EvalQuestion extends BaseEvalQuestion {
  public function __toString()
  {
    return sprintf('%s', $this->getName());
  }
} // EvalQuestion
