<?php


/**
 * Skeleton subclass for representing a row from the 'jury' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri Oct 29 13:36:04 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Jury extends BaseJury {
  public function __toString()
  {
    return sprintf('%s', $this->getName());
  }
} // Jury
