<?php


/**
 * Skeleton subclass for representing a row from the 'project_jury' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri Nov 12 11:55:53 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProjectJury extends BaseProjectJury {
  public function __toString()
  {
    return sprintf('%s %s', $this->getProject(), $this->getJury());
  }

  public function getMyMarks()
  {
    $elem = EvaluationPeer::retrieveByProjectJuryId($this->getId());
    if ($elem == null)
    {
        $value = 0;
    }
    else
    {
        $value = $elem->getTotal();
    }
    return $value;
  }
} // ProjectJury
