<?php


/**
 * Skeleton subclass for performing query and update operations on the 'project' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri Oct 29 13:36:05 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProjectPeer extends BaseProjectPeer {

    public static function doSelectEvalProjects()
    {
        $criteria = new Criteria();
        $criteria->add(ProjectPeer::BLOG, '', Criteria::NOT_EQUAL);
        $criteria->add(ProjectPeer::RSS, '', Criteria::NOT_EQUAL);

        return self::doSelect($criteria);
    }
} // ProjectPeer
