generator:
  class: sfPropelGenerator
  param:
    model_class:           EvalQuestion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EvalQuestion
    plural:                EvalQuestions
    route_prefix:          eval_question
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, point, eval_type, comment]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
