generator:
  class: sfPropelGenerator
  param:
    model_class:           ProjectJury
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ProjectJury
    plural:                ProjectJurys
    route_prefix:          project_jury
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        peer_method: doSelectByUser
        display: [ jury, project ]
        batch_actions: {}
        object_actions:
            evaluate: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
