generator:
  class: sfPropelGenerator
  param:
    model_class:           Evaluation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Evaluation
    plural:                Evaluations
    route_prefix:          evaluation
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: {}
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      eval:    ~
