generator:
  class: sfPropelGenerator
  param:
    model_class:           Project
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Project
    plural:                Projects
    route_prefix:          project
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        peer_method: doSelectEvalProjects
        batch_actions: {}
        object_actions:
          _edit:   ~
          _delete: ~
          choose:  ~
        display: [=name, description, blog, rss, code]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
