generator:
  class: sfPropelGenerator
  param:
    model_class:           Project
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Project
    plural:                Projects
    route_prefix:          project
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, description, blog, rss, code]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
